### ISSUE TITLE
use in  VFP reports

### ISSUE THREAD

**Issue by benrojas01** [atlopes/DPIAwareManager#1]
good afternoon

this solution applies to reports ?

thanks

**Comment by atlopes** [comment]
Hi,

If your only issue is with reports and not with the size of forms and other graphic objects in text-scaled monitors, this solution may represent an unnecessary overhead.

For the single purpose of getting VFP9 reports correctly printed, a simple dpi-aware manifest will do.

**Comment by benrojas01** [comment]
Thanks Antonio, but my question is if your solution also applies to reports

**Comment by atlopes** [comment]
Hi,

The DPIAwareManager class only deals with screen and form objects, but it indirectly affects reports.

In general, VFP reports render as designed, except when the ENGINEBEHAVIOR is set to 90, and the system is running on a monitor with a text scale above 100%.

In this case, integrating a DPI-aware manifest into the executable is sufficient to make reports render as expected. Since linking such manifest is a requirement for the manager to operate, using the class also solves the rendering problem with reports.
